@db1
Feature: 新建下载任务

  Background:
    Given open the "splSearch.SearchPage" page for uri "/search/"

  @dbstats
  Scenario Outline: 新建下载任务3个
    Given I set the parameter "SearchInput" with value "<splQuery>"
    And I click the "DateEditor" button
    And I click the "Today" button
    And I click the "SearchButton" button
    And I wait for "2000" millsecond
    And I wait for element "SearchStatus" change text to "搜索完成!"

    And I wait for "2000" millsecond
    And I wait for "saveAsOther" will be visible
    Then I click the "saveAsOther" button
    Then I click the "downloadButton" button
    Then I set the parameter "DownloadName" with value "<name>"
    Then I set the parameter "MaxLineNum" with value "<lNum>"
#    Then I choose the "<unit>" from the "MaxLineDropdown"
    Then I choose the "<fileType>" from the "DocumentTypeList"
    Then I choose the "<encode>" from the "DocumentEncodeList"
    Then I click the "CreateDownloadTask" button
    And I wait for "2000" millsecond
    Then I will see the success message "提交成功，请到设置-下载管理页查看下载状态！"

    Examples: 新建成功
      | name                                         | lNum | unit | fileType | encode | splQuery                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | gf_dapper_tracing                            | 100  | 行    | CSV      | UTF-8  | tag:gf_dapper* AND dapper.msg.traceId:\"511f8756ce1d0b8a\" dapper.msg.duration:>0 \| table dapper.msg.id, dapper.msg.parentId, dapper.class, dapper.msg.duration, dapper.msg.timestamp, dapper.msg.binaryAnnotations[].value, collector_recv_timestamp \| sort by dapper.msg.id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | stats_cnt                                    | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| stats count() as cnt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | kvextract_request_query_table                | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| sort by -apache.x_forward \| limit 10 \| kvextract apache.request_query pairdelim=\"&\" kvdelim=\"=\" \| table apache.status, apache.resp_len, gw_address, gw_port                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | kvextract_xiaomi_jsonurl                     | 100  | 行    | CSV      | UTF-8  | tag:sample04061424_xiaomi_3 \| kvextract json.url pairdelim=\"&\" kvdelim=\"=\" \| table stamp, props                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | kvextract_h3c_parse_msg_clean_keys_true      | 100  | 行    | CSV      | UTF-8  | tag:sample04061424_h3c_kv_1 \| parse field=raw_message \"(?<message>DEV_TYPE[\S+\s+]+)rule_ID(?<message1>[\S+\s+]+)\" \| fields message \| kvextract message clean_keys=true pairdelim=\";\" kvdelim=\"=\" \| fields -message \| table *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | kvextract_h3c_parse_msg                      | 100  | 行    | CSV      | UTF-8  | tag:sample04061424_h3c_kv_1 \| parse field=raw_message \"(?<message>DEV_TYPE[\S+\s+]+)rule_ID(?<message1>[\S+\s+]+)\" \| fields message \| kvextract message pairdelim=\";\" kvdelim=\"=\" \| fields -message \| table *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | appendcols_override_index2                   | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| stats count(apache.clientip)  \| appendcols override=true  [[ index=*  tag:sample04061424_display \| stats count(apache.clientip) ]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | eval_printf_1                                | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| sort by apache.x_forward \| limit 1 \| eval aa=printf(\"%04d\",1) \| table aa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | eventstats_sample_avglen                     | 100  | 行    | CSV      | UTF-8  | tag:sample04061424  \| where apache.resp_len > 100 &&  apache.resp_len < 500 \| eventstats  avg(apache.resp_len) as avglen \| table apache.resp_len, avglen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
#      | fillnull_string_to_null_resplen_sample       | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 AND NOT apache.resp_len:* \| fillnull value=\"66\" apache.resp_len \ eval type_apache.resp_len = typeof(apache.resp_len) \| table apache.resp_len, type_apache.resp_len, apache.x_forward \| sort by apache.x_forward                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | download_cnt_clientip_bystatus_csv_sample    | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart \| chart count() over apache.clientip by apache.status \| download filename=\"download_cnt_clientip_bystatus_csv_sample\" fileformat=\"csv\"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | makeresults_sample                           | 100  | 行    | CSV      | UTF-8  | \| makeresults count = 1 \| eval tag = \"sample04061424\" \| map \"starttime=\"now/d\" endtime=\"now/d+24h\" tag:$tag$ \| table apache.status, apache.resp_len,apache.clientip \| sort by apache.status, apache.resp_len,apache.clientip\"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | geostats_sample_count                        | 3000 | 行    | CSV      | UTF-8  | tag:vendors_461 \| geostats latfield=vendors.VendorLatitude longfield=vendors.VendorLongitude count() as cnt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | search_all_samepre_tag_count                 | 100  | 行    | CSV      | UTF-8  | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424* \| top 100 tag \| sort by count,tag                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | search_all_nopre_tag_count                   | 100  | 行    | CSV      | UTF-8  | index=* starttime=\"now/d\" endtime=\"now/d+24h\" NOT tag:sample04061424* \| top 10 tag \| sort by tag                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | not_eval_stats_top                           | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 AND (NOT apache.status:200) \| eval status = apache.status \| stats top(status,10)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#      | parse_chinese_char_maxmatch100_exceed_rawlen | 100  | 行    | CSV      | UTF-8  | tag:sample04061424_chinese_5 \| limit 1 \| parse field=raw_message \"(?<first_chinese_char>[\u4e00-\u9fa5])\" max_match=100 \| table first_chinese_char                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | eval_match_query                             | 100  | 行    | CSV      | UTF-8  | tag:\"sample04061424\" AND apache.request_query:* \| eval r_match1 = match(apache.request_query, \"b.*e\") \| eval r_match2 = match(apache.request_query, \"^bcd\") \| table apache.request_query, r_match1, r_match2, apache.x_forward \| sort by  apache.x_forward                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | stats_hg                                     | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| stats hg(apache.status,50)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | stats_pct                                    | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| stats pct(raw_message_length,1,5,25,50,75,95,99)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | stats_min_timestamp_formatdate               | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart \| stats min(timestamp) as min_time by apache.status \| eval t_min_time = typeof(min_time) \| eval long_min_time = tolong(min_time) \| eval f_min_time = formatdate(log_min_time,\"HH:mm:ss\") \| sort by +apache.status                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | stats_stats_avg                              | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| stats count() as cnt, max(apache.status) as r_max by apache.clientip \| stats avg(cnt) by r_max                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | top_2_clientip_by_path                       | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| top 20 apache.clientip by apache.request_path \| sort by count, apache.request_path, apache.clientip                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | bucket_movingavg_rollingstd_eval             | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+7h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts\| stats count(appname) as count_ by ts\| movingavg count_,5 as ma\| rollingstd count_,5 as rs\| eval lower=ma-1*rs\| eval upper=ma+1*rs\| eval outlier=if(count_>upper\|\|count_<lower, count_, 0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | bucket_timeranges_24h                        | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_apachesample_dawn \| bucket timestamp timeranges=((MIN,-48h),(-48h,-24h),(-24h,MAX)) as ret_timeranges \| table ret_timeranges                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | rollingstd                                   | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+13h\" tag:sample04061424_apachesample_dawn\| bucket timestamp span=1h as ts \| stats avg(apache.resp_len) as avg_resp_len by ts  \| rollingstd avg_resp_len,10 as resp_len_rolling_std                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | bucket_stats_autoregress_eval_where_fields   | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart \| bucket timestamp span=1h as ts \| stats count(appname) as count_app by ts \| eval time=formatdate(ts,\"HH:mm:ss\") \| autoregress count_app p=6 \| eval rate=if(empty(count_app_p6),0,abs(count_app_p6-count_app)) \| eval result=if(empty(count_app_p6),0,1) \| where result>0 \| fields count_app,time,count_app_p6,rate,result                                                                                                                                                                                                                                                                                                                                                                                               |
      | tran_stats_cmd_limit                         | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| transaction apache.status, apache.method \| stats count() as cnt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | tran_with_stats_fromstate_tostate            | 100  | 行    | CSV      | UTF-8  | tag:\"t_with\" \| transaction json.sid with states a, b, c in json.module results by flow \| stats count() by fromstate, tostate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | last_name_mvappend                           | 100  | 行    | CSV      | UTF-8  | tag:sample04061424 \| eval fullName=mvappend(apache.clientip, \"middle value\", apache.method) \| table apache.clientip, apache.method,fullName \| stats last(fullName)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | append_status_sub_eval                       | 100  | 行    | CSV      | UTF-8  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_apachesample_dawn \| stats avg(apache.resp_len) \| eval day=\"the group dawn\" \| append  [[ starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| stats avg(apache.resp_len) \| eval day=\"the group display\" \| append [[ starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart \| stats avg(apache.resp_len) \| eval day=\"the group chart\" ]] ]]                                                                                                                                                                                                                                                                                                                                                   |
      | sub_join_percent                             | 100  | 行    | CSV      | UTF-8  | tag:\"sample04061424\" \| stats count(logtype) as count_all by apache.clientip \| sort by count_all \| limit 50 \| join type=left apache.clientip [[ tag:\"sample04061424\" AND apache.status:[400 TO 499] \| stats count(logtype) as count_400 by apache.clientip]] \| join type=left apache.clientip [[ tag:\"sample04061424\" AND apache.status:[500 TO 599] \| stats count(logtype) as count_500 by apache.clientip ]] \| join type=left apache.clientip [[tag:\"sample04061424\" AND apache.resp_len:>1000 \| stats count(logtype) as len_1000 by apache.clientip]] \| eval rate_400=if(empty(count_400),0,count_400/count_all) \| eval rate_500=if(empty(count_500),0,count_500/count_all) \| eval rate_len_1000=if(empty(len_1000),0,len_1000/count_all) \| sort by count_all, apache.clientip |
#      | name                                      | 100  | 行    | CSV      | UTF-8  |                                                                                                                                                                                                                                                                              |

  @dbevent
  Scenario Outline: 新建事件数3个
    Given I set the parameter "SearchInput" with value "<splQuery>"
    And I click the "DateEditor" button
    And I click the "Today" button
    And I click the "SearchButton" button
    And I wait for "2000" millsecond
    And I wait for element "SearchStatus" change text to "搜索完成!"

    And I wait for "2000" millsecond
    Then I click the "DownloadEvent" button
    Then I set the parameter "DownloadName" with value "<name>"
    Then I set the parameter "MaxLineNum" with value "<lNum>"
    Then I choose the "<fileType>" from the "DocumentTypeList"
    Then I choose the "<encode>" from the "DocumentEncodeList"
    Then I click the "CreateDownloadTask" button
    And I wait for "2000" millsecond
    Then I will see the success message "提交成功，请到设置-下载管理页查看下载状态！"

    Examples:
      | name                                   | lNum | unit | fileType | encode | splQuery                                                                                             |

      | tran_ip_maxopen_max                    | 100  | 行    | JSON     | UTF-8  | (logtype:apache AND tag:sample04061424) \| transaction apache.clientip maxopenevents=10 maxevents=10 |
#      | tran_apachelen_sort                    | 100  | 行    | JSON     | UTF-8  | tag:sample04061424 \| transaction  apache.resp_len \| sort by apache.resp_len                         |
#      | tran_count_where                       | 100  | 行    | JSON     | UTF-8  | tag:sample04061424 \| transaction apache.resp_len \| where _count>0                                   |
#      | bug_tran_with                          | 100  | 行    | CSV      | UTF-8  | tag:t_with \| transaction json.sid with states a, b, c in json.module results by flow                 |
      | search_generall                        | 100  | 行    | TXT      | UTF-8  | tag:sample04061424                                                                                   |
      | index_yotta_regex                      | 100  | 行    | TXT      | UTF-8  | index=yotta tag:sample04061424 AND  /[0][8]0{2,2}/                                                   |
      | search_eventcount                      | 100  | 行    | TXT      | UTF-8  | tag:sample04061424 AND apache.referer_domain:\"m5.baidu.com\" AND apache.clientip:\"23.166.125.53\"  |
      | search_highlight_resp_len_char         | 100  | 行    | TXT      | UTF-8  | tag:sample04061424 AND apache.resp_len:\"93\"                                                        |
      | search_highlight_clientip              | 100  | 行    | TXT      | UTF-8  | tag:sample04061424 AND apache.clientip:23*                                                           |
      | search_highlight_before_capital_letter | 100  | 行    | TXT      | UTF-8  | tag:highlight_huawei_10 \"the message is\"                                                           |
#      | name | 100  | 行    | CSV      | UTF-8  |       |



