@dellagacytrend
Feature: 删除冗余趋势图

  Scenario Outline: 删除冗余趋势图
    Given open the "trend.ListPage" page for uri "/trend/"
    When I set the parameter "SearchInput" with value "<name>"
    And I wait for "2000" millsecond
    And the data name is "{'column':'0','name':'<name>'}" then i click the "删除" button
    Then I will see the message "确认删除 [<name>] ?"
    When I click the "EnsureButton" button
    Then I will see the success message "删除成功"

    Examples:
      | name                                     |
      |table|
      |sequence|
      |sundiagram|
      |sundiagramcolor|
      |chain|
      |test|
      |test(副本)|
      |trendtest1|
      |trendtest1(副本)|
      |test_bar|
      |test_bar|
      |test_bar(副本)|
      |test_area|
      |test_line|
      |test_scatter|
      |attackmap(副本)|
      |lim|
      |12333333|
      |12|
      |数据集无|
      |数据集汇聚|
      |数据集继承|
      |qk111|
      |23213|
      |32132|
      |mc|
      |mysql_connection|
      |single_test|
      |父子无|
      |父子汇聚|
      |父子继承|
      |zf_test|
      |qq|
      |1231232|
      |2132|
      |auto_1888_det|
      |auto_1888_det|
      |auto_1888_det|
      |auto_1888_det|
      |auto_1888_det2|
      |bin-line|
      |2132|
      |12345|
      |日志类型统计|
      |仪表盘所有|
      |licm_steamstats|
      |test|
      |bin-single|
      |test|
      |bin-funnel|
      |bin-single|
      |bin-liquidfill|
      |0121jnd1|
      |bin-single|
      |bin-single-2|
      |0122table|
      |table|
      |单值图|
      |linux非登录安全事件|
      |事件详情|
      |用户在线时长|
      |linux定时任务执行趋势|
      |登录方式分布|
      |登录失败用户分布-1|
      |登录失败用户分布|
      |错误事件模块分布|
      |登录失败事件|
      |登录成功用户分布|
      |登录趋势|
      |登录成功源IPtop10|
      |最新十分钟在线用户明细|
      |用户执行定时任务次数|
      |最近十分钟在线用户|
      |安全事件趋势|
      |最新20条错误事件明细|
      |用户拥有定时任务数量|
      |错误事件趋势|
      |中间件_nginx_请求失败状态码分布|
      |nginx错误日志请求地址top10|
      |nginx_request分布占比|
      |Nginx错误详情|
      |中间件_nginx_请求来源分布|
      |nginx错误日志referrer_Top10|
      |nginx错误日志趋势|
      |中间件_nginx_请求ip地址top10|
      |中间件_nginx_请求路径top10|
      |中间件_nginx_请求浏览器分布|
      |中间件_nginx_请求操作系统分布|
      |中间件_nginx_流量趋势|
      |nginx错误等级分布|
      |中间件_nginx_请求方式趋势图|
      |中间件_nginx_请求失败状态码分布|
      |nginx错误日志请求地址top10|
      |nginx_request分布占比|
      |Nginx错误详情|
      |中间件_nginx_请求来源分布|
      |nginx错误日志referrer_Top10|
      |nginx错误日志趋势|
      |中间件_nginx_请求ip地址top10|
      |中间件_nginx_请求路径top10|
      |中间件_nginx_请求浏览器分布|
      |中间件_nginx_请求操作系统分布|
      |中间件_nginx_流量趋势|
      |nginx错误等级分布|
      |中间件_nginx_请求方式趋势图|
      |中间件_nginx_请求失败状态码分布|
      |nginx错误日志请求地址top10|
      |nginx_request分布占比|
      |Nginx错误详情|
      |中间件_nginx_请求来源分布|
      |nginx错误日志referrer_Top10|
      |nginx错误日志趋势|
      |中间件_nginx_请求ip地址top10|
      |中间件_nginx_请求路径top10|
      |中间件_nginx_请求浏览器分布|
      |中间件_nginx_请求操作系统分布|
      |中间件_nginx_流量趋势|
      |nginx错误等级分布|
      |中间件_nginx_请求方式趋势图|
      |柱状图|
      |bar|
      |column|
      |single_trend|
      |123|
      |1234|
      |6666|
      |12|
      |12|
      |chain_color|
      |sun_中文134|
      |test_radar|
      |testTableColor|
      |table_Order|
      |table_Dimension|
      |table_Sun|
      |table_Chord|
      |table_Sankey|
      |table_Force|
      |table_Sankey_Mult|
      |table_Rangeline|
      |table_Multiaxis|
      |table_Heatmap|
      |table_Regionmap|
      |table_Attackmap_World|
      |table_Attackmap_China|
      |table_Regionmap_Jiangsu|
      |table_Single|
      |table_Wordcloud|
      |table_Radar_Matr|
      |table_Funnel|
      |table_Single_Range|
      |table_Liquidfill|
      |LineChart_2477|
      |AreaChart_2005|
      |ScatterChart_2491|
      |ColumnChart_2499|
      |AreaChart_Pile|
      |ColumnChart_Pile|
      |ScatterChart_bubbles|
      |LineChart_2479_Smooth|
      |LineChart_2479_ConnectEmptyData|
      |AreaChart_2483_Smooth|
      |AreaChart_2483_ConnectEmptyData|
      |ScatterChart_2492_limit|
      |ColumnChart_2500_limit|
      |LineChart_2477|
      |AreaChart_2005|
      |ScatterChart_2491|
      |AreaChart_Pile|
      |ColumnChart_Pile|
      |ScatterChart_bubbles|
      |LineChart_2479_Smooth|
      |LineChart_2479_ConnectEmptyData|
      |AreaChart_2483_Smooth|
      |AreaChart_2483_ConnectEmptyData|
      |ScatterChart_2492_limit|
      |ColumnChart_2500_limit|
      |Pie_2503|
      |Rose_2858|
      |Bar_2676|
      |Sun_2850|
      |Bar_只展示名称_柱状外左侧|
      |Bar_只展示名称_柱状外右侧|
      |Bar_只展示名称_柱状内中央|
      |Bar_只展示名称_柱状内靠左侧|
      |Bar_只展示名称_柱状内靠右侧|
      |Bar_展示全部_柱状外左侧|
      |Bar_展示全部_柱状外右侧|
      |Bar_展示全部_柱状内中央|
      |Bar_展示全部_柱状内靠左侧|
      |Bar_展示全部_柱状内靠右侧|
      |Pie_不展示|
      |Rose_不展示|
      |Bar_不展示|
      |Pie_只展示名称|
      |Pie_展示全部|
      |Rose_展示全部|
      |Chord_2505|
      |Sankey_2507|
      |Force_2511|
      |Force_repulsion|
      |Sankey_Multistage|
      |Rangeline_2516|
      |Multiaxis_2523|
      |Heatmap_2539|
      |Regionmap_2545|
      |Attackmap_World_2542|
      |Attackmap_China_2543|
      |Regionmap_China_2546|
      |Regionmap_Jiangsu_2547|
      |Statisticalmap_2098|
      |Statisticalmap_2797|
      |Statisticalmap_2098_param|
      |Statisticalmap_2797_param|
      |Single_2549|
      |Wordcloud_2625|
      |Radar_2633|
      |Funnel_2654|
      |Single_icon|
      |Single_cnt|
      |Single_font1|
      |Single_font2|
      |Single_backgr|
      |Single_trend|
      |Single_rangeF|
      |Single_rangeB|
      |Single_prec1_1000on__before|
      |Single_prec2_1000off_back_after|
      |Ring_onefield|
      |Ring_twofields|
      |Ring_table_1r_4c|
      |Ring_table_1r_3c_colors|
      |Liquidfill_percent|
      |Radar_2635|
      |Funnel_2858|
      |Matrixheatmap_2660|
      |Matrixheatmap_2661|
      |Chain_2831|
      |Sequence_2805|
      |Table_Test|
      |timechart_3247_line|
      |timechart_3094_area|
      |timechart_3248_area|
      |timechart_3096_scatter|
      |timechart_3249_scatter|
      |timechart_3098_column|
      |timechart_3250_column|
      |timechart_3093_line|
      |timechart_3095_area|
      |timechart_3097_scatter|
      |timechart_3099_column|
      |table_Order|
      |table_Dimension|
      |table_Sun|
      |table_Chord|
      |table_Sankey|
      |table_Force|
      |table_Sankey_Mult|
      |table_Rangeline|
      |table_Multiaxis|
      |table_Heatmap|
      |table_Regionmap|
      |table_Attackmap_World|
      |table_Attackmap_China|
      |table_Regionmap_Jiangsu|
      |table_Single|
      |table_Wordcloud|
      |table_Radar_Matr|
      |table_Funnel|
      |table_Single_Range|
      |table_Liquidfill|
      |仪表盘饼状图|
      |AutoCreateApp|
      |验证仪表盘全局时间|
      |仪表盘所有|
      |regionmap_daymode|
      |内存使用率趋势图_WIN|
      |主机内存使用情况预测分析_WIN|
      |磁盘高使用率主机数_WIN|
      |内存高使用率主机数_WIN|
      |主机性能一览图_WIN|
      |内存高使用率主机列表_WIN|
      |主机CPU健康度_WIN|
      |磁盘空闲率_TOP5|
      |CPU使用率趋势图_WIN|
      |网络高出口流量主机列表_WIN|
      |进程占用CPU百分比TOP5_WIN|
      |网卡入口流量图_WIN|
      |网络高入口流量主机列表_WIN|
      |主机内存健康度_WIN|
      |主机CPU使用情况预测分析_WIN|
      |磁盘高使用率主机列表_WIN|
      |CPU高使用率主机数_WIN|
      |磁盘使用率_TOP5_WIN|
      |磁盘读IO_TOP5_WIN|
      |网络高出口流量主机数_WIN|
      |网卡出口流量图_WIN|
      |Windows运维异常概览|
      |网络高入口流量主机数_WIN|
      |磁盘写IO_TOP5_WIN|
      |磁盘空闲率趋势图_WIN|
      |CPU高使用率主机列表_WIN|
      |stst_map_params|
      |statsmap_parameters|
      |LineChart_2477|
      |AreaChart_2005|
      |ScatterChart_2491|
      |ColumnChart_2499|
      |AreaChart_Pile|
      |ColumnChart_Pile|
      |ScatterChart_bubbles|
      |LineChart_2479_Smooth|
      |LineChart_2479_ConnectEmptyData|
      |AreaChart_2483_Smooth|
      |AreaChart_2483_ConnectEmptyData|
      |ScatterChart_2492_limit|
      |ColumnChart_2500_limit|
      |Pie_2503|
      |Rose_2858|
      |Bar_2676|
      |Sun_2850|
      |Bar_只展示名称_柱状外左侧|
      |Bar_只展示名称_柱状外右侧|
      |Bar_只展示名称_柱状内中央|
      |Bar_只展示名称_柱状内靠左侧|
      |Bar_只展示名称_柱状内靠右侧|
      |Bar_展示全部_柱状外左侧|
      |Bar_展示全部_柱状外右侧|
      |Bar_展示全部_柱状内中央|
      |Bar_展示全部_柱状内靠左侧|
      |Bar_展示全部_柱状内靠右侧|
      |Pie_不展示|
      |Rose_不展示|
      |Bar_不展示|
      |Pie_只展示名称|
      |Rose_只展示名称|
      |Pie_展示全部|
      |Rose_展示全部|
      |Chord_2505|
      |Sankey_2507|
      |Force_2511|
      |Force_repulsion|
      |Sankey_Multistage|
      |Rangeline_2516|
      |Multiaxis_2523|
      |Heatmap_2539|
      |Regionmap_2545|
      |Attackmap_World_2542|
      |Attackmap_China_2543|
      |Regionmap_China_2546|
      |Regionmap_Jiangsu_2547|
      |Statisticalmap_2098|
      |Statisticalmap_2797|
      |Statisticalmap_2098_param|
      |Statisticalmap_2797_param|
      |Single_2549|
      |Wordcloud_2625|
      |Radar_2633|
      |Funnel_2654|
      |Single_icon|
      |Single_cnt|
      |Single_font1|
      |Single_font2|
      |Single_backgr|
      |Single_trend|
      |Single_rangeF|
      |Single_rangeB|
      |Single_prec1_1000on__before|
      |Single_prec2_1000off_back_after|
      |Ring_onefield|
      |Ring_twofields|
      |Ring_table_3r_2c|
      |Ring_table_1r_4c|
      |Ring_table_1r_3c_colors|
      |Liquidfill_percent|
      |Funnel_2858|
      |Matrixheatmap_2660|
      |Matrixheatmap_2661|
      |Chain_2831|
      |Chain_2982|
      |Sequence_2805|
      |Table_Test|
      |timechart_3092_line|
      |timechart_3247_line|
      |timechart_3094_area|
      |timechart_3248_area|
      |timechart_3096_scatter|
      |timechart_3249_scatter|
      |timechart_3098_column|
      |timechart_3250_column|
      |timechart_3093_line|
      |timechart_3095_area|
      |timechart_3097_scatter|
      |91919|
      |123|
      |多Y|
      |heatmap_draganddrop|
      |chord_drag_and_drop|
      |13|
      |AutoCreateApp|
      |gc_test|
      |gc_test_geostatsmap|
      |父子汇聚|
      |父子继承|
      |本月|
      |123|
      |123|
      |123|
      |123|
      |sxjtest|
      |gc_test_onlinemap_groupby|
      |gc_test_geostatsmap_general|
      |验证仪表盘全局时间|
      |仪表盘所有|
      |验证仪表盘全局时间|
      |验证仪表盘全局时间|
      |仪表盘message|
      |仪表盘return|
      |仪表盘workflow|
      |仪表盘力图|
      |仪表盘区划地图|
      |仪表盘区间图|
      |仪表盘和弦图|
      |仪表盘多Y轴图|
      |仪表盘字符云图|
      |仪表盘循序图|
      |仪表盘攻击地图|
      |仪表盘旭日图|
      |仪表盘条形图|
      |仪表盘桑基图|
      |仪表盘水球图|
      |仪表盘漏斗图|
      |仪表盘热力地图|
      |bin-pie-rendertype|
      |bin-sunburst-rendertype|
      |123|
      |1234|
      |traceTableTest|
      |zjq-tracing|
      |status_pie|
      |pie_rendertype|
      |SJZFT|