Feature: 验证宏

  Background:
    Given open the "macroSearch.ListPage" page for uri "/macro/"
    And I wait for "2000" millsecond

  @vdlmacro1
  Scenario Outline:
    Then I compare source file "<name>.csv" with target macro files "macro_<name>.csv"

    Examples:
      | name      | macroSearch                                      | splQuery1                                        |
      | two_param | tag:sample04061424 \| eval x=`me_if_excp_2(1,2)` | tag:sample04061424 \| eval x=`me_if_excp_2(1,2)` |
#      | mne_if_3                                    | tag:sample04061424 \| eval x=`mne_if_3(1,2,3)` \| table x                                                                                                                                                                                                                                                                                | tag:sample04061424 \| eval x="if(isstr(3),1-2,1+2)" \| table x                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
#      | map_opt_count_2                             | `map_opt_count_2("count", "count")`                                                                                                                                                                                                                                                                                                      | tag:\"sample04061424\" \| eval txt=\"count\"\| limit 1 \| table txt \| map \" tag:\"sample04061424\" \| stats count(timestamp) \"                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
#      | map_eval_resplen_stats_count_2              | `map_eval_resplen_stats_count_2("count",69)`                                                                                                                                                                                                                                                                                             | tag:\"sample04061424\" \| eval resp_len=$int_resp_len$ \| limit 1 \| table resp_len \| map \" tag:\"sample04061424\" \| stats $fun_name$() \"                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
#      | huanbi_2                                    | `huanbi_2("apache",count)`                                                                                                                                                                                                                                                                                                               | starttime=\"now/d\" endtime=\"now\" appname:apache \| bucket timestamp span=1h as ts \|stats count() as count_ by ts\| eval hour=formatdate(tolong(ts),\"HH\")\|eval line=\"今天\"\|append [[starttime=\"-1d/d\" endtime=\"now/d\" appname:apache \| bucket timestamp span=1h as ts\|stats count() as count_ by ts\| eval hour=formatdate(tolong(ts),\"HH\")\|eval line=\"昨天\"]] \| append [[starttime=\"-7d/d\" endtime=\"-6d/d\" appname:apache \| bucket timestamp span=1h as ts\|stats count() as count_ by ts\| eval hour=formatdate(tolong(ts),"\HH\")\|eval line=\"一周前\"]] \| rename count_ as \"请求量\" |
#      | timechart_hour_1                            | `timechart_hour_1(1)`                                                                                                                                                                                                                                                                                                                    | tag:sample04061424 \| timechart span=1h count() as res_count \| where res_count>0 \| eval f_time=formatdate(_time)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
