@vdl
Feature: 处理下载结果

  Background:
    Given open the "splSearch.OfflineTaskPageNohup" page for uri "/download/#"

  @vdlxtable1
  Scenario Outline: 下载比较
    Then I compare source bucket file "<name>.csv" with target bucket files "<name>.csv"

    Examples: 新建成功
      | name                                                | splQuery                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | autoregress_sample                                  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=30m as ts \| stats count(appname) as count_app by ts \| eval time=formatdate(ts,\"HH:mm:ss\") \| autoregress count_app p=6                                                                                                                                                                                                                                                                          |
      | earliest_timestamp_by_ip                            | tag:sample04061424_apachesample_dawn \| stats earliest(timestamp) as earliest_time by apache.clientip \| eval f_earliest_time=formatdate(earliest_time,\"HH:mm:SS\") \| sort by apache.clientip                                                                                                                                                                                                                                                                                                             |
      | latest_timestamp_by_ip                              | tag:sample04061424_apachesample_dawn \| stats latest(timestamp) as latest_time by apache.clientip \| eval f_latest_time =formatdate(latest_time,\"HH:mm:ss.SSS\")                                                                                                                                                                                                                                                                                                                                           |
      | first_timestamp                                     | tag:sample04061424_apachesample_dawn \| stats first(timestamp) as first_time \| eval f_first_time =formatdate(first_time)                                                                                                                                                                                                                                                                                                                                                                                   |
      | first_timestamp_by_ip                               | tag:sample04061424_apachesample_dawn \| stats first(timestamp) as first_time by apache.clientip \| eval f_first_time =formatdate(first_time)                                                                                                                                                                                                                                                                                                                                                                |
      | last_timestamp                                      | tag:sample04061424_apachesample_dawn \| stats last(timestamp) as last_time \| eval f_last_time =formatdate(last_time)                                                                                                                                                                                                                                                                                                                                                                                       |
      | last_timestamp_by_ip                                | tag:sample04061424_apachesample_dawn \| stats last(timestamp) as last_time by apache.clientip \| eval f_last_time=formatdate(last_time)                                                                                                                                                                                                                                                                                                                                                                     |
      | makecontinuous_sample                               | \| makeresults count=2 \| streamstats count() as cnt \| eval time=case(cnt==2,relative_time(now(),\"+1d\"), cnt==1, now()) \| makecontinuous time span=3h                                                                                                                                                                                                                                                                                                                                                   |
      | timechart_timewrap_align_now                        | starttime=\"now/d\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h align=now                                                                                                                                                                                                                                                                                                                                                                                                 |
      | timechart_span12h_timewrap_1d                       | starttime=\"now-7d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=12h count() as cnt  \| timewrap 1d                                                                                                                                                                                                                                                                                                                                                                                  |
      | timechart_span1h_timewrap_1d                        | starttime=\"now-3d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 1d                                                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_span1h_timewrap_3d                        | starttime=\"now-7d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt max(apache.resp_len) as max_len by apache.status \| timewrap 3d                                                                                                                                                                                                                                                                                                                                   |

  @vdlxtable0
  Scenario Outline: 下载比较
    Then I compare source bucket file "<name>.csv" with target bucket files "<name>.csv"

    Examples: 新建成功
      | name                                                | splQuery                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | chart_over_timestamp_span1h                         | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display  \| chart count() over timestamp span=\"1h\"                                                                                                                                                                                                                                                                                                                                                                                           |
      | chart_over_timestamp_span1d                         | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() over timestamp span=\"1d\"                                                                                                                                                                                                                                                                                                                                                                                            |
      | chart_bins3_span1h                                  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() over timestamp bins=3 span=\"1h\"                                                                                                                                                                                                                                                                                                                                                                                     |
      | chart_bins24_span1h                                 | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() over timestamp bins=24 span=\"1h\"                                                                                                                                                                                                                                                                                                                                                                                    |
      | chart_sep_sample                                    | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart sep=\"-sep分格-\" count() max(apache.resp_len) over timestamp span=\"1h\" by apache.status                                                                                                                                                                                                                                                                                                                                      |
      | chart_sep_format                                    | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart sep=\"-sep分格-\" format=\"$AGG\|format分格\|$VAL\" count() max(apache.resp_len) over timestamp span=\"1h\" by apache.status                                                                                                                                                                                                                                                                                                      |
      | chart_sep_format1                                   | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart sep=\"-sep分格-\" format=\"$VAL\|format分格\|$AGG\" count() max(apache.resp_len) over timestamp span=\"1h\" by apache.status                                                                                                                                                                                                                                                                                                      |
      | chart_bins10_span30m                                | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() max(apache.resp_len) over timestamp bins=10 span=\"30m\"                                                                                                                                                                                                                                                                                                                                                              |
      | chart_bins10_span30m_startindex2_endindex7          | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() max(apache.resp_len) over timestamp bins=10 span=\"30m\"                                                                                                                                                                                                                                                                                                                                                              |
      | chart_bins10_span30m_startindex4_endindex7          | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() max(apache.resp_len) over timestamp bins=10 span=\"1h\" startindex=4 endindex=7                                                                                                                                                                                                                                                                                                                                       |
      | chart_bins10_span30m_startindex4_endindex7_bystatus | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart count() max(apache.resp_len) over timestamp bins=10 span=\"1h\" startindex=4 endindex=7 by apache.status                                                                                                                                                                                                                                                                                                                      |
      | chart_limit_one_field                               | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart limit=5 count() max(apache.resp_len) over timestamp span=\"1h\" by apache.status                                                                                                                                                                                                                                                                                                                                              |
      | chart_multi_params_by_clientip                      | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart sep=\"-sep分格-\" format=\"$AGG\|format分格\|$VAL\" limit=5 cont=false count() as cnt max(apache.resp_len) over timestamp span=\"1h\" bins=4 startindex=1 endindex=4 by apache.clientip bins=3                                                                                                                                                                                                                                    |
      | chart_multi_params_by_status_bins1                  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart sep=\"-sep分格-\" format=\"$AGG\|format分格\|$VAL\" limit=5 cont=false count() as cnt max(apache.resp_len) over timestamp span=\"1h\" bins=4 startindex=1 endindex=4 by apache.status bins=1                                                                                                                                                                                                                                      |
      | chart_multi_params_by_resplen_bins3                 | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| chart sep=\"-sep分格-\" format=\"$AGG\|format分格\|$VAL\" limit=5 cont=false count() as cnt max(apache.status) over timestamp span=\"1h\" bins=4 startindex=1 endindex=4 by apache.resp_len bins=3                                                                                                                                                                                                                                      |
      | bucket_ts_stats_sum_eval                            | (logtype:apache AND tag:\"sample04061424_chart\") \| bucket timestamp span=1m as ts \| stats sum(apache.resp_len) as sum_len by ts,apache.status \| eval time=formatdate(ts,\"HH:mm:ss\")                                                                                                                                                                                                                                                                                                                   |
      | bucket_stats_eval_movingavg                         | starttime=\"now/d\" endtime=\"now/d+24h\"  tag:\"sample04061424_chart\"\| bucket timestamp span=1m as ts \| stats sum(apache.resp_len) as sum_resp_len by ts \| eval time=formatdate(ts,\"HH:mm:ss\") \| movingavg sum_resp_len,3 as moving_avg_resp_len                                                                                                                                                                                                                                                    |
      | bucket_1h_stats_count                               | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart \| bucket timestamp span=1h as ts \| stats count(apache.clientip) as c_ip by ts                                                                                                                                                                                                                                                                                                                                                          |
      | starttime_bucket_ts_sum_eval                        | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_chart\" \| bucket timestamp span=1h as ts \| stats sum(apache.resp_len) as sum_len by ts \| eval time=formatdate(ts,\"HH:mm:ss\")                                                                                                                                                                                                                                                                                                            |
      | starttime_bucket_ts_count_eval_formatdate           | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_chart\" \| bucket timestamp span=1h as ts \| stats count(apache.resp_len) as sum_len by ts \| eval time=formatdate(ts,\"HH:mm:ss\")                                                                                                                                                                                                                                                                                                          |
      | bucket_stats_autoregress                            | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_chart\" \| bucket timestamp span=1h as ts \| stats count() as count_app by ts \| eval time=formatdate(ts,\"HH:mm:ss\") \| autoregress count_app p=3                                                                                                                                                                                                                                                                                          |
      | schedule_append_bucket_count_geoisp                 | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts \| stats count(apache.geo.isp) as count_ by apache.geo.isp, ts \| eval date_hour=tolong(formatdate(ts,\"HH\")) \| rename apache.geo.isp as group_line \| sort by +date_hour, +group_line \| append [[index=schedule starttime=\"-2d\" endtime=\"-d/d\" schedule_name:pip_task\|stats avg(ip_count) as count_ by date_hour\|eval group_line=\"base_line\"\|sort by +date_hour,+group_line]] |
      | filldown_after_bucket_avg_eval                      | starttime=\"now/d\" endtime=\"now/d+12h\" tag:sample04061424_chart \| bucket timestamp span=1h as ts \| stats avg(apache.resp_len) as a_ by ts \| eval b=a_ \| filldown b                                                                                                                                                                                                                                                                                                                                   |
      | filldown_after_bucket_stats_avg                     | starttime=\"now/d\" endtime=\"now/d+12h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts \| stats avg(apache.resp_len) as avg_resp_len by ts  \| filldown avg_resp_len                                                                                                                                                                                                                                                                                                              |
      | bucket_movingavg_rollingstd_eval                    | starttime=\"now/d\" endtime=\"now/d+7h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts\| stats count(appname) as count_ by ts\| movingavg count_,5 as ma\| rollingstd count_,5 as rs\| eval lower=ma-1*rs\| eval upper=ma+1*rs\| eval outlier=if(count_>upper\|\|count_<lower, count_, 0)                                                                                                                                                                                          |
      | top_count_percent                                   | tag:sample04061424 \| top 11 apache.clientip  countfield=clientip_count  percentfield=clientip_percent                                                                                                                                                                                                                                                                                                                                                                                                      |
      | earliest_timestamp                                  | tag:sample04061424_apachesample_dawn \| stats earliest(timestamp) as earliest_time \| eval f_earliest_time=formatdate(earliest_time,\"HH:mm:SS\")                                                                                                                                                                                                                                                                                                                                                           |
      | latest_timestamp                                    | tag:sample04061424_apachesample_dawn \| stats latest(timestamp) as latest_time \| eval f_latest_time =formatdate(latest_time,\"HH:mm:ss.SSS\")                                                                                                                                                                                                                                                                                                                                                              |
      | first_bucket_count_ip                               | tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts \| stats count(apache.clientip) as c_ip by ts \| stats first(c_ip)                                                                                                                                                                                                                                                                                                                                                                   |
      | earliest_bucket_count_ip                            | tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts \| stats count(apache.clientip) as c_ip by ts \| stats earliest(c_ip)                                                                                                                                                                                                                                                                                                                                                                |
      | bucket_stats_es                                     | starttime=\"now/d\" endtime=\"now/d+7h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=1h as ts \| stats es(apache.status) by ts                                                                                                                                                                                                                                                                                                                                                            |
      | rollingstd                                          | starttime=\"now/d\" endtime=\"now/d+13h\" tag:sample04061424_apachesample_dawn\| bucket timestamp span=1h as ts \| stats avg(apache.resp_len) as avg_resp_len by ts  \| rollingstd avg_resp_len,10 as resp_len_rolling_std                                                                                                                                                                                                                                                                                  |
      | timechart_sample                                    | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart count() \| eval f_time = formatdate(_time,\"HH:mm:ss\")                                                                                                                                                                                                                                                                                                                                                                   |
      | timechart_sample_count_span1h                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h max(apache.resp_len) as cnt                                                                                                                                                                                                                                                                                                                                                                                       |
      | timechart_sample_count_span1h_bystatus              | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt by apache.status                                                                                                                                                                                                                                                                                                                                                                                   |
      | timechart_sample_avg_span1h                         | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h avg(apache.resp_len) as avg_len                                                                                                                                                                                                                                                                                                                                                                                   |
      | timechart_sep_byip_span1h                           | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart AND ('apache.clientip':221.226.97.92 OR 'apache.clientip':117.136.79.162)  \| timechart sep=\":\" span=1h count() as cnt max(apache.resp_len) by apache.clientip                                                                                                                                                                                                                                                                         |
      | timechart_sep_bydomain_span1h                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart AND ('apache.clientip':221.226.97.92 OR 'apache.clientip':117.136.79.162)  \| timechart sep=\":\" span=1h count() as cnt max(apache.resp_len) by apache.referer_domain                                                                                                                                                                                                                                                                   |
      | timechart_sep_bystatus_span1h                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart sep=\":\" span=1h count() as cnt max(apache.resp_len) by apache.status                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_format                                    | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart sep=\"-sep分格-\" format=\"$VAL\|分格2\|$AGG\" span=1h count() as cnt by apache.status                                                                                                                                                                                                                                                                                                                                        |
      | timechart_format1                                   | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart sep=\"-sep分格-\" format=\"$VAL\|分格2\|$AGG\" span=1h count() as cnt max(apache.resp_len) as ma by apache.status                                                                                                                                                                                                                                                                                                             |
      | timechart_limit_sample_onecol                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart limit=1 span=1h avg(apache.resp_len) as avg_len by apache.clientip                                                                                                                                                                                                                                                                                                                                                        |
      | timechart_limit_by_one                              | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_display\" \| timechart span=1h limit=5 count() max(apache.resp_len) by apache.status                                                                                                                                                                                                                                                                                                                                                         |
      | timechart_bins_sample                               | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_display\" \| timechart bins=10 span=30m count()                                                                                                                                                                                                                                                                                                                                                                                              |
      | timechart_span30m_bins3                             | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=30m bins=3 count() max(apache.resp_len) by apache.status                                                                                                                                                                                                                                                                                                                                                             |
      | timechart_minspan2h_bins40                          | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart minspan=2h bins=40 count()                                                                                                                                                                                                                                                                                                                                                                                                |
      | timechart_minspan30m_bins40                         | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart minspan=30m bins=40 count()                                                                                                                                                                                                                                                                                                                                                                                               |
      | timechart_minspan30m_bins4                          | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart minspan=30m bins=4 count()                                                                                                                                                                                                                                                                                                                                                                                                |
      | timechart_bins100_bymethod                          | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h bins=100 count() max(apache.resp_len) by apache.method                                                                                                                                                                                                                                                                                                                                                            |
      | timechart_startindex_endindex                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_display\" \| timechart bins=8 span=30m startindex=1 endindex=8 count() max(apache.status)                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_startindex_endindex1                      | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_display\" \| timechart bins=10 span=30m startindex=1 endindex=8 count() max(apache.status) by apache.resp_len                                                                                                                                                                                                                                                                                                                                |
      | timechart_sample_all_params                         | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424_display\" \| timechart sep=\":\" format=\"$VAL--$AGG\" cont=true span=30m bins=100 startindex=1 endindex=8 limit=5 count() min(apache.resp_len) by apache.status                                                                                                                                                                                                                                                                             |
      | timechart_sample_all_params1                        | starttime=\"now/d\" endtime=\"now/d+24h\" tag:\"sample04061424\"  \| eval x=len(tostring(apache.request_path)) \| timechart sep=\",\" format=\"$VAL**$AGG\" cont=true limit=5 bins=10 minspan=1m span=10m max(x) as ma count() as cnt \| where ma>0 && cnt>0                                                                                                                                                                                                                                                |
      | timechart_cont_true                                 | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart cont=true span=1h count()                                                                                                                                                                                                                                                                                                                                                                                                 |
      | timechart_cont_false                                | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart cont=false span=1h count()                                                                                                                                                                                                                                                                                                                                                                                                |
      | timechart_cont_bystatus_true                        | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart sep=\":\" span=30m cont=false count() by apache.status                                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_cont_bystatus_false                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart sep=\":\" span=30m cont=false count() by apache.status                                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_timewrap_8h                               | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h                                                                                                                                                                                                                                                                                                                                                                                     |
      | timechart_timewrap_10h                              | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 10h                                                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_timewrap_series_short                     | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h series=short                                                                                                                                                                                                                                                                                                                                                                        |
      | timechart_timewrap_timeformat                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h series=exact timeformat=\"H\"                                                                                                                                                                                                                                                                                                                                                       |
      | timechart_timewrap_align_end                        | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h align=end                                                                                                                                                                                                                                                                                                                                                                           |
      | timechart_timewrap_formatedate                      | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h \| eval f_time = formatdate(_time,\"HH:mm:ss\")                                                                                                                                                                                                                                                                                                                                     |

  @vdleval
  Scenario Outline: 下载比较
    Then I compare source download file "<name>.csv" with target download files "<name>.csv"

    Examples:
      | name                                          | splQuery                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | lookup_case_sensitive_match_false_sample | \| makeresults \| eval company=\"baidu\" \| lookup DNS, Company /data/rizhiyi/spldata/lookup/dns.csv on company=Company  case_sensitive_match=false |
      | lookup_case_sensitive_match_true_sample | \| makeresults \| eval company=\"baidu\" \| lookup DNS, Company /data/rizhiyi/spldata/lookup/dns.csv on company=Company  case_sensitive_match=true |
      | lookup_case_sensitive_match_false_nodns | \| makeresults \| eval company=\"baidu\" \| lookup dns, Company /data/rizhiyi/spldata/lookup/dns.csv on company=Company  case_sensitive_match=false |
      | lookup_case_sensitive_match_false_nohost | \| makeresults \| eval company=\"baidu\" \| lookup HOST, Company /data/rizhiyi/spldata/lookup/dns.csv on company=Company  case_sensitive_match=false |
      | eval_md5_sha1_sha256_sample | tag:sample04061424 \| eval cip=apache.clientip \| eval r_md5=md5(cip), r_sha1=sha1(cip), r_sha256=sha256(cip) \| table cip,r_md5,r_sha1,r_sha256 |
      | eval_md5_sha1_sha256_sample1 | tag:sample04061424 \| limit 1 \| eval cip=\"All#123456\" \| eval r_md5=md5(cip), r_sha1=sha1(cip), r_sha256=sha256(cip) \| table cip,r_md5,r_sha1,r_sha256 |
      | ipmath_sample | tag:sample04061424 \| sort by apache.x_forward \| limit 1 \| eval cip=apache.clientip \| eval testip=is_valid_ip(cip),r_ip2long=ip2long(cip) \| eval r_long2ip=long2ip(r_ip2long) \| table cip, testip, r_ip2long, r_long2ip |
      | ipmath_expand_ip_range_to_cidr | tag:sample04061424 \| sort by apache.x_forward \| limit 1 \| eval cip=apache.clientip \| eval r_mvappend=mvappend(cip,\"192.168.1.200\") \|eval r_cidr=expand_ip_range_to_cidr(r_mvappend) \| table cip, r_mvappend, r_cidr |
      | distinct_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424* \| stats distinct(timestamp),estdc(timestamp),dc(timestamp) |
      | iplocation_sample | \| makeresults \| eval tmpip=\"1.157.46.56\" \| fields -timestamp \| iplocation tmpip |
      | iplocation_sample1 | \| makeresults \| eval ip=split(\"202.106.0.20 2400:da00::dbf:0:100 117.50.11.11\", \" \")  \| mvexpand ip \| fields -timestamp \| iplocation ip |
      | iplocation_clientip_sample2 | tag:sample04061424 \| sort by apache.x_foward \| table apache.clientip \| iplocation apache.clientip |
      | iplocation_clientip_zero | \| makeresults \| eval ip=0  \| mvexpand ip \| fields -timestamp \| iplocation ip |
      | unpivot_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:top_info1152 \| stats avg(json.net.packets_recv), latest('json.net.packets_recv'), es('json.net.packets_recv') \| unpivot |
      | unpivot_bygroup_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:top_info1152 \| stats latest('json.disk.used'), es('json.disk.used') by json.disk.path \| unpivot |
      | unpivot_bygroup_header_field | starttime=\"now/d\" endtime=\"now/d+24h\" tag:top_info1152 \| stats latest('json.disk.used'), es('json.disk.used') by json.disk.path \| unpivot header_field=json.disk.path column_name=function |
      | unpivot_bygroup_header_field_unpivot | starttime=\"now/d\" endtime=\"now/d+24h\" tag:top_info1152 \| stats latest('json.disk.used'), es('json.disk.used') by json.disk.path \| unpivot header_field=json.disk.path column_name=function \| unpivot header_field=function |
      | foreach_avg_disk_used | starttime=\"now/d\" endtime=\"now/d+24h\" tag:top_info1152 \| timechart avg(json.disk.used) as a by json.disk.path \| foreach a* [[ eval '<<FIELD>>'='<<FIELD>>'/1024/1024/1024 ]] \| fields -_time |
      | foreach_json_sample | \| makeresults \| eval json.as=\"a\", json.a2=\"b\",json.a3=\"c\" \| foreach json.* [[ eval test = if(empty(test),\"\",tet+\"\")+\"<<FIELD>>\"]] \| fields -timestamp |
      | foreach_apache | tag:sample04061424 \| sort by apache.x_foward \| table apache.geo.l* \| foreach apache.g* [[ eval new_field='<<FIELD>>']] |
      | autofield_jpath_output_city_sample | tag:json_jpath_mv_where \| jpath output=city path=\"a[*].city\" |
      | autofield_spl_eval_empty | tag:sample04061424 \| eval path_is_empty=empty(apache.resp_len) |
      | autofield_spl_eval_match | tag:\"sample04061424\" AND apache.request_query:* \| eval r_match1 = match(apache.request_query, \"b.*e\") |
      | autofield_spl_eval_parse | tag:sample04061424 AND  apache.x_forward:1\| parse \"(?<digital_list>\\\\d+)\" max_match=100 |
      | autofield_spl_eval_kvextract | tag:sample04061424 \| sort by -apache.x_forward \| limit 3 \| kvextract apache.request_query clean_keys=true pairdelim=\"&\" kvdelim=\"=\" |
      | eval_not_in_resp_len | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval is_in = in(apache.resp_len, -1, -2) \| table apache.resp_len, is_in, apache.x_forward \| sort by apache.x_forward \| limit 10 |
      | eval_in_resp_len_v_null | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval is_in = in(apache.resp_len, null) \| table apache.resp_len, is_in, apache.x_forward \| sort by apache.x_forward \| limit 10 |
      | eval_in_flist_loat_v_float | starttime=\"now/d\" endtime=\"now/d+24h\" tag:traceip_list_3 \| eval is_in=in(json.cost,4.993,8.973 ) \| table json.cost, is_in |
      | eval_in_forward_v_params | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval is_in=in(apache.x_forward, apache.x_forward) \| table apache.status, apache.resp_len, is_in, apache.x_forward \| sort by apache.x_forward \| limit 10 |
      | eval_in_refererdomain_v_params | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval is_in=in(apache.referer_domain, apache.referer_domain) \| table apache.resp_len, is_in, apache.referer_domain \| sort by apache.referer_domain \| limit 10 |
      | eval_in_resp_len_v_single_where | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval is_in=in(apache.resp_len, apache.status,4653, 2017, 2020) \| where is_in==true \| table apache.status, apache.resp_len, is_in, apache.x_forward \| sort by apache.x_forward |
      | eval_in_resp_len_v_list | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval len_list=mvappend(4653, 2017, 2020) \| eval is_in=in(apache.resp_len, apache.status, len_list) \| where is_in==true \| table apache.status, apache.resp_len, is_in, apache.x_forward \| sort by apache.x_forward |
      | eval_in_list_v_single_resp_len | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| eval len_list=mvappend(4653, 2017, 2020) \| eval is_in=in(len_list, apache.resp_len, apache.status) \| where is_in==true \| table apache.status, apache.resp_len, is_in, apache.x_forward \| sort by apache.x_forward |
      | eval_in_data_list_v_data_list | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 3 \| eval list123_1=mvappend(1,2,3) \| eval list123_2=mvappend(1,2,3) \| eval is_in=in(list123_1, list123_2) \| table list123_1,is_in |
      | eval_in_data_list_v_data_list_single | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 3 \| eval list123_1=mvappend(1,2,3) \| eval list123_2=mvappend(4, 5, 6) \| eval is_in=in(list123_1, list123_2) \| table list123_1,is_in |
      | eval_in_string_list_v_string_list | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 1 \| eval citylist=mvappend(\"beijing\", \"tianjin\", \"Shanghai\") \| eval is_in=in(citylist, citylist) \| table citylist, is_in |
      | eval_in_string_list_v_string_list_false | starttime=\"now/d\" endtime=\"now/d+24h\" tag:jpath_mvzip_1 \| eval citylist=mvappend(\"beijing1\", \"tianjin1\", \"Shanghai1\") \| eval is_in=in(json.a[].city, citylist) \| table citylist, json.a[].city, is_in |
#      | kvdict_sample_stats_rename_outputlookup | starttime=\"now/d\" endtime=\"now/d+24h\"  tag:sample04061424 \| stats count() as cnt by apache.status, apache.clientip \| rename apache.status as status, apache.clientip as clientip \| where cnt>2 \| outputlookup kvstoresample |
#      | kvdict_sample_inputlookup | \| inputlookup kvstoresample |
#      | kvstore_sample_stats_rename_outputlookup_csv | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart \| eval int_x_forward= tolong(apache.x_forward) \| sort by +int_x_forward \| limit 10 \| stats count() as cnt by apache.clientip, apache.status \| outputlookup cnt_ip_status.csv |
#      | kvstore_sample_inputlookup_csv | \| inputlookup cnt_ip_status.csv |
      | partition_status_stats_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| partition 5 by apache.status [[ stats count() by apache.status ]] |
      | partition_status_chart_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| partition 3 by apache.status [[ chart count() over apache.status span=\"100\" ]] |
      | newfields_keep_ipstatus_limit_table_ipstatus_tag | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| fields + apache.status, apache.clientip \| limit 10 \| table apache.status, apache.clientip, tag |
      | newfields_keep_ipstatus_table_tagmethod | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields + apache.status, apache.clientip \| table tag, apache.method, apache.status |
      | limit_newfields_batch_keep_apache_remove_apacher_table | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields + apache.* \| fields - apache.g*, apache.r*, apache.timestamp,apache.ua \| table apache.* |
      | newfields_remove_tagappname_table_tagstatus | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| fields - appname, tag \| table tag, apache.status |
      | newfields_remove_tag_keep_tag_table | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields - tag \| fields + tag \| table tag |
      | newfields_batch_keep_apache_limit_count_byip | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| fields + apache.* \| limit 13 \| stats count() by apache.clientip |
      | newfields_keep_noexistfield | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields + noexistfield1, noexistfield2 \| table noexistfield1, noexistfield2, tag |
      | newfields_remove_noexistfield | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields - noexistfield1, noexistfield2 \| table apache.x_forward, apache.resp_len, apache.referer_domain, apache.clientip |
      | newfields_batch_remove_spacesplit_table | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields - apache.* raw_message  \| table tag, apache.x_forward |
      | newfields_batch_remove_apache_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields - apache.*, raw_message \| table tag, apache.status |
      | newfields_keep_ipstatus_limit_sample | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| sort by apache.x_forward \| limit 10 \| fields + apache.status, apache.clientip \| table apache.status, apache.clientip, tag |
      | limit_newfields_batch_keep_apache_count_byip | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424 \| sort by apache.x_forward \| limit 10 \| fields + apache.* \| stats count() by apache.clientip |
      | bug_onetag_sort_timestamp1 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424* AND logtype:apache  \| sort by timestamp \| table tag, apache.clientip |
      | bug_onetag_sort_timestamp2 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424* AND logtype:apache  \| sort by +timestamp \| table tag, apache.clientip |
      | bug_top_limit_sort1_Mindex | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424*  \| top 10 appname \| limit 10 |
      | bug_stats_limit_sort2_Mindex | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424*  \| top 10 appname \| limit 10 \|sort by count |
      | bug_sort_timestamp1 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424* \| sort by timestamp \| table tag |
      | bug_sort_timestamp2 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424* \| sort by +timestamp \| eval f_formatdate = formatdate(timestamp)\| table appname,f_formatdate |
      | bug_top_limit_sort1 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424*  \| top 10 appname \| limit 20 |
      | bug_top_limit_sort2 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424*  \| top 10 appname \| limit 10 \|sort by count |
      | bug_stats_limit_sort1 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424* \| stats count() as ct by appname \| limit 10 |
      | bug_stats_limit_sort2 | index=* starttime=\"now/d\" endtime=\"now/d+24h\" tag: sample04061424* \| stats count() as ct by appname \| limit 10 \| sort by +ct |
      | bug_where_count1 | tag:sample04061424 AND apache.resp_len:* \| eval trade_time=todouble(apache.resp_len) \| where trade_time>0.0 \| stats count() as count_ |
      | bug_where_count2 | tag:sample04061424 AND apache.resp_len:>0 \| eval trade_time=todouble(apache.resp_len) \| where trade_time>0.1 \| stats count() as count_ |
      | bug_count_extend_stats | tag:sample04061424 \| stats count() as cnt by apache.status \| stats extend_stat(cnt) |
      | bug_max_if | tag:sample04061424 \| stats max(timestamp) by apache.method \| eval a = if(empty(apache.method), 1, 0) |
      | bug_max_as_value | tag:sample04061424 \| stats max(apache.status) as value |
      | bug_count_ip_sort | tag:sample04061424 \| stats count(apache.status) as status by apache.clientip \| sort by +status |
      | bug_formatdate_Asia | tag:sample04061424_apachesample_dawn \| eval new_time = 1552237948000 \| eval f_timestamp = formatdate(new_time, \"yyyy-MM-dd HH:mm:ss.SSS\", \"Asia/Shanghai\") \| table f_timestamp,new_time |
      | bug_now_where_count_app | starttime=\"now/d\" endtime=\"now\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=10m as ts\|stats count(appname) as count_app by ts \| eval time=formatdate(ts,\"HH:mm:ss\")\| where count_app>0 |
      | bucket_formatdate_where_count_larger3 | starttime=\"now/d\" endtime=\"now\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=10m as ts\|stats count(appname) as count_app by ts\| eval time_dis=formatdate(now()-ts, \"HH:mm:ss\") \| where count_app>3 |
      | rate_sample | tag:top_info \| eval retpath=json.disk.path \| eval retused=json.disk.used \| eval used=tolong(retused) \| bucket timestamp span=10m as timestamp \| table used,retpath,timestamp \| stats rate(used) by timestamp,retpath |
      | transpose_count | tag:sample04061424 \| stats count() as cnt by apache.method, apache.status \| transpose row=apache.method column=apache.status valuefield=cnt |
      | transpose_pct | tag:sample04061424 \| stats pct(apache.status,1,5,25,50,75,95,99) as pct_ by apache.method \| transpose row=pct_.1 column=apache.method valuefield=pct_.5 |
      | transpose_table | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_apachesample_dawn \| table apache.geo.longitude,apache.geo.latitude, apache.clientip \| transpose row=apache.geo.longitude column=apache.geo.latitude valuefield=apache.clientip |
      | transpose_eval_table | tag:sample04061424_chart \| stats avg(apache.resp_len) as avglen by  apache.clientip \| eval int_avglen = floor(avglen) \| sort by avglen  \| transpose row=apache.clientip column=int_avglen valuefield=avglen |
      | transpose_bucket_stats_eval_autoregress | starttime=\"now/d\" endtime=\"now+d/d\" tag:sample04061424_apachesample_dawn \|bucket timestamp span=1h as ts\|stats count() as count_app by ts\|eval time=formatdate(ts,\"HH:mm:ss\") \|autoregress count_app p=3 \|transpose row=ts column=time valuefield=count_app |
      | esma_sample | starttime=\"now/d\" endtime=\"now+d/d\" tag:\"sample04061424_apachesample_dawn\" \| bucket timestamp span=1h as ts \| stats count() as cnt by ts \| esma cnt timefield=ts |
      | esma_sample1 | starttime=\"now/d\" endtime=\"now+d/d\" tag:\"sample04061424_apachesample_dawn\" \| bucket timestamp span=1h as ts \| stats avg(apache.resp_len) as cnt by ts \| esma cnt timefield=ts \|eval r_fmt_time=formatdate(ts) |
      | esma_futurecount | starttime=\"now/d\" endtime=\"now+d/d\" tag:\"sample04061424_apachesample_dawn\" \| bucket timestamp span=1h as ts \| stats count() as cnt by ts \| esma cnt timefield=ts futurecount=30 \|eval new_tt=formatdate(ts,\"HH:mm:ss\") |
      | esma_where_join | starttime=\"now-1d/d\" endtime=\"now/d\" tag:sample04061424_chart \| bucket timestamp span=1h as ts \| stats avg(apache.status) as avg_ by ts \| esma avg_ timefield=ts futurecount=24 \| eval r_fmt=formatdate(ts)  \| where typeof(_predict_avg_)==\"double\" \| eval time = formatdate(ts, \"HH:mm\") \| table time, _predict_avg_ \| join type=left time [[ starttime=\"now/d\" endtime=\"now/d+24h\"  tag:\"sample04061424_chart\" \| bucket timestamp span=1h as ts \| stats avg(apache.status) as avg_ by ts \| eval time = formatdate(ts, \"HH:mm\") \| table time, avg_ ]] |

