@allnewsaved
Feature: 新建全部已存搜索用例

  Background:
    Given open the "splSearch.SearchPage" page for uri "/search/"
    And I wait for element "SearchStatus" change text to "搜索完成!"

  @nallsaved0
  Scenario Outline: 批量新建搜索
    When I set the parameter "SearchInput" with value "<splQuery>"
    Then I choose1 the "新建" from the "SavedSearchList"
    And I wait for loading complete
#    And I wait for loading invisible

    And I set the parameter "SavedSearchName" with value "<name>"
#    And I choose the "<searchResName>" from the "GroupComboBox"
    And I click the "EnsureCreateSavedSearch" button
    And I wait for loading complete
    Then I will see the success message "创建成功"

    Examples: 保存成功
      | name     | splQuery                                  |
      | autoregress_sample                                  | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_apachesample_dawn \| bucket timestamp span=30m as ts \| stats count(appname) as count_app by ts \| eval time=formatdate(ts,\"HH:mm:ss\") \| autoregress count_app p=6                                                                                                                                                                                                                                                                          |
      | earliest_timestamp_by_ip                            | tag:sample04061424_apachesample_dawn \| stats earliest(timestamp) as earliest_time by apache.clientip \| eval f_earliest_time=formatdate(earliest_time,\"HH:mm:SS\") \| sort by apache.clientip                                                                                                                                                                                                                                                                                                             |
      | latest_timestamp_by_ip                              | tag:sample04061424_apachesample_dawn \| stats latest(timestamp) as latest_time by apache.clientip \| eval f_latest_time =formatdate(latest_time,\"HH:mm:ss.SSS\")                                                                                                                                                                                                                                                                                                                                           |
      | first_timestamp                                     | tag:sample04061424_apachesample_dawn \| stats first(timestamp) as first_time \| eval f_first_time =formatdate(first_time)                                                                                                                                                                                                                                                                                                                                                                                   |
      | first_timestamp_by_ip                               | tag:sample04061424_apachesample_dawn \| stats first(timestamp) as first_time by apache.clientip \| eval f_first_time =formatdate(first_time)                                                                                                                                                                                                                                                                                                                                                                |
      | last_timestamp                                      | tag:sample04061424_apachesample_dawn \| stats last(timestamp) as last_time \| eval f_last_time =formatdate(last_time)                                                                                                                                                                                                                                                                                                                                                                                       |
      | last_timestamp_by_ip                                | tag:sample04061424_apachesample_dawn \| stats last(timestamp) as last_time by apache.clientip \| eval f_last_time=formatdate(last_time)                                                                                                                                                                                                                                                                                                                                                                     |
      | makecontinuous_sample                               | \| makeresults count=2 \| streamstats count() as cnt \| eval time=case(cnt==2,relative_time(now(),\"+1d\"), cnt==1, now()) \| makecontinuous time span=3h                                                                                                                                                                                                                                                                                                                                                   |
      | timechart_timewrap_align_now                        | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 8h align=now                                                                                                                                                                                                                                                                                                                                                                                                 |
      | timechart_span12h_timewrap_1d                       | starttime=\"now-7d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=12h count() as cnt  \| timewrap 1d                                                                                                                                                                                                                                                                                                                                                                                  |
      | timechart_span1h_timewrap_1d                        | starttime=\"now-3d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt \| timewrap 1d                                                                                                                                                                                                                                                                                                                                                                                    |
      | timechart_span1h_timewrap_3d                        | starttime=\"now-7d\" endtime=\"now/d+24h\" tag:sample04061424_display \| timechart span=1h count() as cnt max(apache.resp_len) as max_len by apache.status \| timewrap 3d                                                                                                                                                                                                                                                                                                                                   |
      #event
      | sub_download                                  | [[ tag:\"sample04061424\"\| stats avg(apache.resp_len) as avg_len by apache.clientip \| sort by +avg_len ]] \| sort by timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | search_verify_chart_log                       | starttime=\"now/d\" endtime=\"now/d+24h\" tag:sample04061424_chart                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | search_regex_json                             | tag:sample04061424_regex_json_100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | search_json_sdyd_41                           | tag:sample04061424_json_sdyd_41                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | search_json_sdyd_float                        | tag:sample04061424_json_sdyd_float_59                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | search_alert_yctv                             | tag:sample04061424_yctv_100 AND (NOT \"errno 104\") AND (NOT \"code 0\") AND (NOT \"errno 111\") AND (NOT \"errno 106\") AND (NOT \"verify failed\") AND (NOT \"errno 101\") AND (NOT \"errno 115\") AND (NOT \"errno 117\") AND (NOT \"Detect failed\") AND (NOT \"errno 109\") AND (NOT \"Job failed\") AND (NOT \"inner error\")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | first_sub_inner_ip                            | [[ tag:\"sample04061424\"\| stats count(apache.clientip) by apache.clientip, apache.method \| limit 2 \| fields apache.clientip apache.method ]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | dedup_int                                     | tag:sample04061424 \| dedup 3 apache.status \| sort by timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | dedup_char_keepevents_true                    | tag:sample04061424 \| dedup 3 apache.version keepevents=true \| sort by timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | dedup_char_keepevents_false                   | tag:sample04061424 \| dedup 3 apache.version keepevents=false \| sort by timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | dedup_double_fields_keepevents_true           | tag:sample04061424 \| dedup 3 apache.method, appname keepevents = true \| sort by timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | dedup_double_fields_keepevents_false          | tag:sample04061424 \| dedup 3 apache.status, appname keepevents = false \| sort by timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | dedup_keepempty_true                          | tag:sample04061424_win_sys_20 \| dedup json.Category keepempty = true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | dedup_keepempty_false                         | tag:sample04061424_win_sys_20 \| dedup json.Category keepempty = false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | eval_delete_after_where_step2                 | starttime=\"now/d\" endtime=\"now/d+24h\" tag:spldelete1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
